baseURL = "https://www.bisnis.tech/"
languageCode = "en-us"
title = "Bisnis.TECH"
disableKinds = ["RSS"]

paginate = 1

[taxonomies]
    tag = "tagar"

[outputs]
  home = ["HTML", "AMP"]
  page = ["HTML", "AMP"]
  section = ["HTML", "AMP"]